### ISSUE TITLE
missing go.sum entry error RAM deployment failed in cloud build

### ISSUE THREAD

**Issue by BrunoReboul** [BrunoReboul/ram#129]
# Error:

```bash
Step #1 - "build a fresh ram cli": Already have image: golang
Step #1 - "build a fresh ram cli": go: github.com/BrunoReboul/ram@v0.4.0-rc23: missing go.sum entry; to add it:
Step #1 - "build a fresh ram cli":  go mod download github.com/BrunoReboul/ram
```
 
Occurs on any build, including existing successful build when hitting RETRY

# Root Cause:

[Cloud function GO runtime](https://cloud.google.com/functions/docs/concepts/go-runtime) is bounded to GO v1.13

RAM developper’s GO version is aligned to the same version to avoid using new GO feature that won t be available on cloud functions.

``` bash
go version go1.13.8 linux/amd64
```

Cloud Build environment uses the online GOLANG container that is continuously updated, currently using GO v1.16

```bash
Step #0 - "display go language version": Status: Downloaded newer image for golang:latest
Step #0 - "display go language version": docker.io/library/golang:latest
Step #0 - "display go language version": go version go1.16 linux/amd64
```

With GO 1.16 the -mod option for [automatic updates](https://golang.org/ref/mod#go-mod-file-updates) default value changes

In Go 1.15 and lower, the -mod=mod flag was enabled by default, so updates were performed automatically. Since Go 1.16, the go command acts as if -mod=readonly were set instead: if any changes to go.mod are needed, the go command reports an error and suggests a fix.

# Proposed fix

Update the Cloud Build triggers build steps definition:
add go version to ease troubleshooting by always displaying which version of GO is used by the GOLANG Docker container
Add to the go build command the flag -mod=mod to allow automatic updates

```yaml
steps:
 - name: golang
   args:
     - go
     - version
   id: display go language version
 - name: golang
   args:
     - go
     - build
     - '-mod=mod'
     - ram.go
   id: build a fresh ram cli
```
