### ISSUE TITLE
As Compliance Manager, I want one files (yaml, csv) with all configured constraints so that a text diff tool can be used to compare 1) sets of rules 2) over time

### ISSUE THREAD

**Issue by BrunoReboul** [BrunoReboul/ram#62]
file name: constraints.xaml, constraints.csv
Example of yaml structure:
```yaml
services:
  - name: bq
    rules:
      - name: dataset_location
        constraints:
          - apiVersion: constraints.gatekeeper.sh/v1alpha1
            kind: GCPBigQueryDatasetLocationConstraintV1
            metadata:
              name: myorg_sanboxes_europe_bq
```
File location: in `monitor` folder
Add the file to `.gitiignore` to avoid conflct
make it on anay ramcli execution
